src/main/java/com/rymcu/vertical/core/constant/NotificationConstant.java, src/main/java/com/rymcu/vertical/core/constant/ProjectConstant.java, src/main/java/com/rymcu/vertical/dto/ArticleDTO.java, src/main/java/com/rymcu/vertical/dto/ArticleTagDTO.java, src/main/java/com/rymcu/vertical/dto/Author.java, src/main/java/com/rymcu/vertical/dto/CommentDTO.java, src/main/java/com/rymcu/vertical/entity/Article.java, src/main/java/com/rymcu/vertical/entity/Comment.java, src/main/java/com/rymcu/vertical/mapper/ArticleMapper.java, src/main/java/com/rymcu/vertical/mapper/CommentMapper.java, src/main/java/com/rymcu/vertical/service/ArticleService.java, src/main/java/com/rymcu/vertical/service/CommentService.java, src/main/java/com/rymcu/vertical/service/impl/ArticleServiceImpl.java, src/main/java/com/rymcu/vertical/service/impl/CommentServiceImpl.java, src/main/java/com/rymcu/vertical/service/impl/TagServiceImpl.java, src/main/java/com/rymcu/vertical/util/BaiDuUtils.java, src/main/java/com/rymcu/vertical/util/NotificationUtils.java, src/main/java/com/rymcu/vertical/web/api/article/ArticleController.java, src/main/java/com/rymcu/vertical/web/api/comment/CommentController.java, src/main/java/mapper/ArticleMapper.xml, src/main/java/mapper/CommentMapper.xml, src/main/java/mapper/RoleMapper.xml
- 我的草稿
- 分享文章
- 消息通知
- 文章评论
- 文章去除无效标签
- 角色修改功能无法更新问题修复
- 手机端页脚显示优化
- 增加返回顶部功能
=> 新功能发布,缺陷代码修复,用户体验提升

src/main/java/com/rymcu/vertical/service/impl/ArticleServiceImpl.java, src/main/java/com/rymcu/vertical/task/BaiDuCronTask.java, src/main/java/com/rymcu/vertical/util/BaiDuUtils.java
=> :art: 代码结构及名称变更

src/main/java/com/rymcu/vertical/service/impl/ArticleServiceImpl.java, src/main/java/com/rymcu/vertical/task/BaiDuCronTask.java, src/main/java/com/rymcu/vertical/util/BaiDuUtils.java
=> :art: 代码结构变更

src/main/java/mapper/ArticleMapper.xml
=> 首页不展示划水贴sql条件修改

src/main/java/mapper/CommentMapper.xml, src/main/java/mapper/SearchMapper.xml
🐛 评论模块点击头像跳转个人主页问题修复
🐛 搜索结果中点击`用户`跳转个人主页问题修复
=> 评论模块/搜索结果跳转个人主页问题修复

src/main/java/com/rymcu/forest/config/BaseExceptionHandler.java, src/main/java/com/rymcu/forest/core/service/security/SecurityAspect.java, src/main/java/com/rymcu/forest/core/service/security/annotation/SecurityInterceptor.java, src/main/java/com/rymcu/forest/jwt/aop/RestAuthTokenInterceptor.java, src/main/java/com/rymcu/forest/web/api/bank/WalletController.java, src/main/java/com/rymcu/forest/web/api/exception/BaseApiException.java, src/main/java/com/rymcu/forest/web/api/user/UserInfoController.java
=> 修复了一些已知的安全问题

pom.xml, src/main/java/com/rymcu/forest/core/service/security/SecurityAspect.java, src/main/java/com/rymcu/forest/jwt/service/RedisTokenManager.java, src/main/java/com/rymcu/forest/service/impl/ArticleServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/UserServiceImpl.java, src/main/java/com/rymcu/forest/task/BaiDuCronTask.java, src/main/java/mapper/UserMapper.xml, src/main/resources/log4j2.component.properties
1. 🎨  剔除主动推送百度 SEO 功能
2. 🎨  优化记录最后在线时间代码
3. 🎨 优化代码结构
4. ⬆️ 升级 log4j2 依赖
=> 修复一些已知的安全问题

src/main/java/com/rymcu/forest/mapper/TransactionRecordMapper.java, src/main/java/com/rymcu/forest/service/BankAccountService.java, src/main/java/com/rymcu/forest/service/TransactionRecordService.java, src/main/java/com/rymcu/forest/service/impl/BankAccountServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/NotificationServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/TransactionRecordServiceImpl.java, src/main/java/com/rymcu/forest/web/api/bank/BankAccountController.java, src/main/java/com/rymcu/forest/web/api/bank/BankController.java, src/main/java/com/rymcu/forest/web/api/bank/WalletController.java, src/main/java/com/rymcu/forest/web/api/notification/NotificationController.java, src/main/java/mapper/TransactionRecordMapper.xml
1. 银行卡管理-增加交易记录查看功能
2. 我的钱包-交易记录增加时间段检索功能
=> ✨  新增了一些功能

src/main/java/com/rymcu/forest/mapper/NotificationMapper.java, src/main/java/com/rymcu/forest/service/NotificationService.java, src/main/java/com/rymcu/forest/service/impl/ArticleServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/NotificationServiceImpl.java, src/main/java/com/rymcu/forest/web/api/notification/NotificationController.java, src/main/java/mapper/NotificationMapper.xml, src/main/resources/static/forest.sql
=> 🐛 修复了一些已知 Bug

src/main/java/com/rymcu/forest/util/BaiDuUtils.java, src/main/java/com/rymcu/forest/util/BeanCopierUtil.java, src/main/java/com/rymcu/forest/util/CacheUtils.java, src/main/java/com/rymcu/forest/util/ContextHolderUtils.java, src/main/java/com/rymcu/forest/util/DateUtil.java, src/main/java/com/rymcu/forest/util/Digests.java, src/main/java/com/rymcu/forest/util/ErrorCode.java
个别工具命名优化、注释补全，BeanCopierUtils的getBeanCopier方法实现优化
=> style(utils): 命名优化、注释补全

pom.xml, src/main/java/com/rymcu/forest/dto/ArticleDTO.java, src/main/java/com/rymcu/forest/dto/ArticleTagDTO.java, src/main/java/com/rymcu/forest/dto/Author.java, src/main/java/com/rymcu/forest/lucene/service/impl/LuceneServiceImpl.java, src/main/java/com/rymcu/forest/lucene/service/impl/PortfolioLuceneServiceImpl.java, src/main/java/com/rymcu/forest/lucene/util/ArticleIndexUtil.java, src/main/java/com/rymcu/forest/service/ArticleService.java, src/main/java/com/rymcu/forest/service/TagService.java, src/main/java/com/rymcu/forest/service/impl/ArticleServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/TagServiceImpl.java, src/main/java/com/rymcu/forest/web/api/article/ArticleController.java, src/main/resources/static/forest.sql, src/test/java/com/rymcu/forest/service/ArticleServiceTest.java
涵盖ArticleService单元测试方法:
postArticle
findArticles
findArticleDTOById
findUserArticlesByIdUser
incrementArticleViewCount
updatePerfect
delete
ArticleService将用户获取逻辑转移到Controller中
sql文件新增用户测试数据
=> feat(test): 新增ArticleService部分单元测试,部分功能优化,sql文件新增测试数据

src/main/java/com/rymcu/forest/dto/ArticleDTO.java, src/main/java/com/rymcu/forest/dto/TokenUser.java, src/main/java/com/rymcu/forest/enumerate/TransactionCode.java, src/main/java/com/rymcu/forest/service/BankAccountService.java, src/main/java/com/rymcu/forest/service/impl/ArticleServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/BankAccountServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/SponsorServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/TransactionRecordServiceImpl.java, src/main/java/com/rymcu/forest/web/api/auth/AuthController.java, src/main/java/com/rymcu/forest/web/api/bank/WalletController.java, src/main/resources/static/forest.sql
1. 钱包账号激活接口
2. update forest.sql
=> 🎨 钱包账号激活接口

src/main/java/com/rymcu/forest/config/ShiroConfig.java, src/main/java/com/rymcu/forest/handler/AccountHandler.java, src/main/java/com/rymcu/forest/handler/ArticleHandler.java, src/main/java/com/rymcu/forest/handler/CommentHandler.java
1. 🎨 关闭 shiro RememberMe 功能
2. 🎨 指定 TaskExecutor Bean 名称
=> 🎨 关闭 shiro RememberMe 功能

src/main/java/com/rymcu/forest/lucene/service/impl/PortfolioLuceneServiceImpl.java
=> 修改可能出现的异常,根据备注提示,内容可能有误.

pom.xml, src/main/java/com/rymcu/forest/openai/OpenAiController.java
1. [⬆️ huTool 依赖升级](https://github.com/rymcu/forest/commit/f8b6ab363259752dcd89a11920788d40b6ae924a)
2. [🎨 兼容无返回值情况](https://github.com/rymcu/forest/commit/29fe0d2343f1de107d2f43b7cb71b326839c7cd5)
=> ⬆️ huTool 依赖升级

pom.xml, src/main/java/com/rymcu/forest/util/SSRFUtil.java, src/main/java/com/rymcu/forest/web/api/common/UploadController.java
🐛 初步解决 SSRF 问题 https://github.com/rymcu/forest/issues/149
=> 🐛 初步解决 SSRF 问题 https://github.com/rymcu/forest/issues/149

src/main/java/com/rymcu/forest/util/SSRFUtil.java
=> 🐛 逻辑判断问题修复

src/main/java/com/rymcu/forest/util/SSRFUtil.java
[🐛 增加对当前 host 是否为 IPv4 和 IPv6 地址的判断](https://github.com/rymcu/forest/commit/01c06992ecf5dfb171bab597617c8a89da6c1525)
=> 🐛 增加对当前 host 是否为 IPv4 和 IPv6 地址的判断

src/main/java/com/rymcu/forest/dto/ProductDTO.java, src/main/java/com/rymcu/forest/entity/Product.java, src/main/java/com/rymcu/forest/entity/ProductContent.java, src/main/java/com/rymcu/forest/mapper/ProductMapper.java, src/main/java/com/rymcu/forest/service/ProductService.java, src/main/java/com/rymcu/forest/service/impl/ProductServiceImpl.java, src/main/java/com/rymcu/forest/web/api/admin/AdminArticleController.java, src/main/java/com/rymcu/forest/web/api/common/CommonApiController.java, src/main/java/com/rymcu/forest/web/api/product/ProductController.java, src/main/java/mapper/ProductMapper.xml
=> 🎨 产品信息维护接口

UserManual.md, docker/dev/forest.sql, src/main/java/com/rymcu/forest/enumerate/FileDataType.java, src/main/java/com/rymcu/forest/enumerate/FilePath.java, src/main/java/com/rymcu/forest/service/impl/PortfolioServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/ProductServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/TagServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/TopicServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/UserServiceImpl.java, src/main/java/com/rymcu/forest/web/api/common/UploadController.java, src/main/resources/static/forest.sql
1. 规范文件上传参数
2. 产品模块接口调整
3. update forest.sql
4. update UserManual.md
=> 🎨 规范文件上传参数

pom.xml, src/main/java/com/rymcu/forest/entity/Tag.java, src/main/java/com/rymcu/forest/entity/Topic.java, src/main/java/com/rymcu/forest/service/impl/ProductServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/TagServiceImpl.java, src/main/java/com/rymcu/forest/service/impl/TopicServiceImpl.java, src/main/java/com/rymcu/forest/web/api/product/ProductController.java, src/main/java/mapper/ProductMapper.xml
=> 🎨 标签/专题管理维护功能完善

src/main/java/mapper/ProductMapper.xml
=> 🎨 产品模块接口返回数据增加 tags 字段

pom.xml
=> :bug: 依赖冲突问题修复

pom.xml
=> :bug: 修复日志问题
